control:
  uri: "http://192.0.2.1:8080"
  bind-addr: "192.0.2.1:8080"
ran:
  bind-addr: "198.51.100.1:1234"
  gnbs:
    - "http://192.0.2.2:8080"
  pdu-sessions:
    - gnb: "http://192.0.2.2:8080"
      dnn: "nextmn-lite"

logger:
  level: "trace"
